{"out":"../../Ardustat_Private/Data/\nloaded from file:  ../../Ardustat_Private/Data/pickler/test1.p\nthis experiment will continue from the following state:  {'cycler_dict_hold_volt_max': {'current_limit_at_max_voltage': 'na', 'max_voltage_limit': 1, 'read_delay': 1, 'file_name': 'pickler/test1', 'time_limit_at_max': 10, 'ardustat_id': 25, 'cycles': 0}, 'read_delay': 1, 'DAC2_value': 2.5, 'file_name': 'pickler/test1', 'notes': '', 'current_state': 'rest1 5', 'cycler_dict_hold_volt_min': {'min_voltage_limit': 0, 'current_limit_at_min_voltage': 'na', 'time_limit_at_min': 5, 'read_delay': 1, 'file_name': 'pickler/test1', 'ardustat_id': 25, 'cycles': 0}, 'start_rest_time': 10, 'cycler_dict_cc_discharge': {'time_limit': 5, 'min_voltage_limit': 'na', 'read_delay': 1, 'file_name': 'pickler/test1', 'ardustat_id': 25, 'discharge_current': -0.0036, 'capacity_limit': 'na'}, 'cycler_dict_cc_charge': {'time_limit': 5, 'max_voltage_limit': 'na', 'read_delay': 1, 'file_name': 'pickler/test1', 'ardustat_id': 25, 'charge_current': 0.0036, 'capacity_limit': 'na'}, 'ardustat_id': 25, 'cycles': 5, 'order': ['rest1 5', 'charge', 'hold_voltage_max', 'rest2 5', 'discharge'], 'cycle': 0}\n","outerr":"Traceback (most recent call last):\n  File \"/Users/danny/Ardustat_Private/pithy/code/ardustat_cycler_1108.py\", line 142, in <module>\n    print n.sread()\n  File \"/Users/danny/Ardustat_Private/pithy/code/ardustat_class_0820.py\", line 35, in sread\n    foo = urllib2.urlopen(self.bread)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 127, in urlopen\n    return _opener.open(url, data, timeout)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 404, in open\n    response = self._open(req, data)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 422, in _open\n    '_open', req)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 382, in _call_chain\n    result = func(*args)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 1214, in http_open\n    return self.do_open(httplib.HTTPConnection, req)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 1184, in do_open\n    raise URLError(err)\nurllib2.URLError: <urlopen error [Errno 61] Connection refused>\n","images":[],"exec_time":1873}